### ISSUE TITLE
Incompability with flask.current_app to initialize database from flask.Flask.config

### ISSUE THREAD

**Issue by DarkSuniuM** [aachurin/peewee_migrations#1]
Hello
I have created my `db` object using this code:
```python3
db = PostgresqlDatabase(None)
db.init(current_app.config['DATABASE_NAME'],
        user=current_app.config['DATABASE_USER'],
        password=current_app.config['DATABASE_PASS'],
        host=current_app.config['DATABASE_HOST'],
        port=current_app.config['DATABASE_PORT'])
```
The problem is, `pem` has no access to Flask's app context,
When I try to use `pem` to migrate my database, it returns the following exception:

```python3
Traceback (most recent call last):
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/bin/pem", line 10, in <module>
    sys.exit(run())
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/peewee_migrations/cli.py", line 339, in run
    cli()
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/peewee_migrations/cli.py", line 116, in add
    import_models(model)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/peewee_migrations/cli.py", line 78, in import_models
    module = import_string(path)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/peewee_migrations/cli.py", line 69, in import_string
    module, path = import_module(path)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/peewee_migrations/cli.py", line 56, in import_module
    module = importlib.import_module(path)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/site_pay/models.py", line 2, in <module>
    from db_init import db,BaseModel
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/db_init.py", line 6, in <module>
    db.init(current_app.config['DATABASE_NAME'],
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/alireza/Desktop/Projects/PemPlayground/webservice/venv/lib/python3.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

Did anyone integrated Flask with PEM this way?
How can I fix it?

**Comment by aachurin** [comment]
Show db_init.py

**Comment by aachurin** [comment]
Try to add this line to migrations.json:
`"prerun": "import app; app.app.app_context().push()"`

**Comment by DarkSuniuM** [comment]
> Try to add this line to migrations.json:
> `"prerun": "import app; app.app.app_context().push()"`

It did the job, Sorry I didn't know about `prerun`

**Comment by DarkSuniuM** [comment]
@aachurin 
I tried to use prerun, still doesn't work for me

**Comment by aachurin** [comment]
i checked, it works.
