### ISSUE TITLE
PEM - AttributeError: 'str' object has no attribute '_table'

### ISSUE THREAD

**Issue by camiloiglesias96** [aachurin/peewee_migrations#24]
Hi @aachurin

- Python **3.8.10**
- Pipenv **2022.1.8**
- Peewee Migrations **0.3.30**
- Peewee **3.14.9**

Recently trying to remove a unique index from foreign key PEM returns this traceback

```
Migration error: 'str' object has no attribute '_table'
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/cli.py", line 256, in watch
    result = router.create(tracecode=context, serialize=serialize)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 683, in create
    migrator.migrate()
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 858, in migrate
    self._migrate_models(models_to_migrate)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 905, in _migrate_models
    self._prepare_model(state[pair], *pair)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 942, in _prepare_model
    self.recorder.drop_foreign_key_constraint(field)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 1233, in recorder
    result = obj(*args, **kwargs)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 1389, in drop_foreign_key_constraint
    self.drop_index(model, index._name)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee_migrations/migrator.py", line 1612, in drop_index
    return (model._schema._drop_index(index, safe=False)
  File "/root/.local/share/virtualenvs/bowling_api-kFPkLh21/lib/python3.8/site-packages/peewee.py", line 5770, in _drop_index
    if isinstance(index._table, Table) and index._table._schema:
AttributeError: 'str' object has no attribute '_table'
```

Thats makes impossible remove the unique index from the table

# Code

**center.py**

```
class CenterPeeweeModel(SoftDeleteModel):
    name: str = CharField(null=False, index=True, unique=True)
    lanes: int = IntegerField(null=False, default=0)
    timezone: str = CharField(null=False, max_length=255)

    company: 'CompanyPeeweeModel' = ForeignKeyField(
        model=CompanyPeeweeModel,
        null=False,
        unique=True,
        backref='centers'
    )
```

**company.py**
```
class CompanyPeeweeModel(SoftDeleteModel):
    name: str = CharField(null=False, index=True, unique=True)
    vat: str = CharField(max_length=255, null=False, index=True)
    country: str = CharField(max_length=2, null=False)
    address: str = CharField(null=True)

    class Meta:
        table_name = 'tlb_companies'
```
**command**
```
pem -c ./apps/<app-name>/migrations.json watch
```
`<app-name>` is  a placeholder

**Comment by aachurin** [comment]
Already in 0.3.31

**Comment by camiloiglesias96** [comment]
@aachurin Thank you so much for your soon fix in the package let me test it but thats make me think great things about this package and their evolution for the future :heart:

**Comment by camiloiglesias96** [comment]
@aachurin The package apparently isnt publibshed on PyPi i tried to get your changes but always get the v0.3.30 :disappointed: :sob: 

Thanks a lot
