### ISSUE TITLE
Python enums are not supported in fields parameters when creating migrations

### ISSUE THREAD

**Issue by Bahus** [aachurin/peewee_migrations#6]
Hello! In my projects I actively use built-in enums to store integer/string constants. Here is an example:

```python
from enum import IntEnum
from peewee import *

class MyEnum(IntEnum):
    on = 1
    off = 0

class MyModel(Model):
    class Meta:
        database = db

    value1 = IntegerField(default=1)
    value2 = IntegerField(default=MyEnum.on)
```

This code snippet produces the following error when executing `pem watch`:

```bash
$ pem watch --traceback
Migration error: invalid syntax (<string>, line X)
Traceback (most recent call last):
  File "/python3.7/site-packages/peewee_migrations/cli.py", line 255, in watch
    result = router.create(tracecode=context)
  File "/python3.7/site-packages/peewee_migrations/migrator.py", line 620, in create
    new_snap = self.storage.exec(compiler.module_code)['snapshot']
  File "/python3.7/site-packages/peewee_migrations/migrator.py", line 518, in exec
    code = compile(code, '<string>', 'exec', dont_inherit=True)
  File "<string>", line X
    value2 = IntegerField(default=<MyEnum.on: 1>)
                                  ^
SyntaxError: invalid syntax
```

The problem can be fixed with a workaround:

```python
    value2 = IntegerField(default=int(MyEnum.on))
```

However it looks pretty... ugly? Could you please add support for enums?

**Comment by aachurin** [comment]
it is a standart library, so yes, I can do it

**Comment by aachurin** [comment]
Done
